baseurl = "https://hbs-rcs.github.io/reproducible-research/"
languageCode = "en-us"
title = "Tools for Reproducible Research"
theme = "hugo-theme-learn"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
disqusShortname = "hbs-rcs"
enableEmoji = true

[outputs]
        home = [ "HTML", "RSS", "JSON"]

[params]
	# General information
	description = "A material design theme for documentations."
	copyright = ""

	# Repository
	provider = ""
	repo_url = ""

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = ""
	email   = ""


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
